WebAdmin/WebAdmin/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebAdmin.Controllers
{
    public class SharedController : Controller
    {
        #region
        [ChildActionOnly]
        public ActionResult _AdminHeader()
        {
            return View();
        }

        [ChildActionOnly]
        public ActionResult _AdminLeftMenu()
        {
            return View();
        }
        #endregion
    }
}

WebAdmin/WebAdmin/Views/Shared/_AdminHeader.cshtml
<header class="main-header">
    <a href="#" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini">Dashboard</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg">Dashboard</span>
    </a>
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- User Account: style can be found in dropdown.less -->
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span><i class="fa fa-cog">&nbsp;&nbsp;</i>Logged as  <b>admin</b></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="user-header">
                            <p>
                                admin
                            </p>
                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a class="btn btn-default btn-flat" href="/webadmin/user/profile">Profile</a>
                            </div>
                            <div class="pull-right">
                                <a class="btn btn-default btn-flat" href="/webadmin/auth/logout">Logout</a>
                            </div>
                        </li>
                    </ul>
                </li>
                <!-- Control Sidebar Toggle Button -->
            </ul>
        </div>
    </nav>
</header>

WebAdmin/WebAdmin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>@ViewBag.Title</title>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />

    <script type="text/javascript" src='//cdnjs.cloudflare.com/ajax/libs/knockout/3.3.0/knockout-min.js'></script>

    <script type="text/javascript" src="//code.jquery.com/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>

    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css" />
    <style>
        /* mobile table styles */


    </style>
    <link href="~/Assest/css/dashboard.css" rel="stylesheet" />
    <link href="~/Assest/css/dragula.css" rel="stylesheet" />
    <link href="~/Assest/css/block.css" rel="stylesheet" />
    <link href="~/Assest/css/widget.css" rel="stylesheet" />
    <link href="~/Assest/css/common.css" rel="stylesheet" />
    <link href="~/Assest/css/layout.css" rel="stylesheet" />
    <link href="~/Assest/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Assest/css/select2.css" rel="stylesheet" />
    <link href="~/Assest/css/select2-fixed-width.css" rel="stylesheet" />
    @*<link href="~/Assest/css/jquerydataTables.css" rel="stylesheet" />*@

    <link href="~/Assest/css/AdminLTE.css" rel="stylesheet" />
    <link href="~/Assest/css/_all-skins.css" rel="stylesheet" />
    <link href="~/Assest/css/ToggleSplitter.css" rel="stylesheet" />
    <link href="~/Assest/css/main.css" rel="stylesheet" />
    <link href="~/Assest/css/all.css" rel="stylesheet" />
    <link href="~/Assest/css/purple-skin.css" rel="stylesheet" />
    <link href="~/Assest/css/purple-aside-menu.css" rel="stylesheet" />

    <link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/buttons/1.6.1/css/buttons.dataTables.min.css" rel="stylesheet" />


    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

    <script src="~/Assest/js/dashboard.js"></script>
    <script src="~/Assest/js/block.js"></script>
    <script src="~/Assest/js/icheck.js"></script>
    <script src="~/Assest/js/select2.js"></script>
    <script src="~/Assest/js/bootstrap.js"></script>
    <script src="~/Assest/js/app-default.js"></script>
    <script src="~/Assest/js/demo.js"></script>
    <script src="~/Assest/js/main.js"></script>


    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.print.min.js"></script>

    <script src="~/Assest/js/ToggleSplitter.js"></script>
    <script type="text/javascript">
        dojo.addOnLoad(function () {
            dojo.require('dojox.layout.ToggleSplitter');
        });

    </script>

</head>
<body class="skin-purple hold-transition skin-purple purple-skin">
    <div data-backdrop="static" id="throberContainer" class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" title="Processing...." style="z-index: 100000;">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-body text-center">
                    <div><img src="img/loading.gif" /></img></div>
                    <div>Loading...</div>
                </div>
            </div>
        </div>
    </div>
    <div class="wrapper">
        @{Html.RenderAction("_AdminHeader", "Shared");}
        @{Html.RenderAction("_AdminLeftMenu", "Shared");}
        <div class="content-wrapper clearfix">
            <section class="content">
                @RenderBody()
            </section>
        </div>
    </div>
    <script>
        $(document).ready(function () {
            $('.listing-table').DataTable({
                dom: 'Bfrtip',
                buttons: [
                    'copy', 'csv', 'excel', 'pdf', 'print'
                ]
            });
        });       
        //        $('.treeview.active').removeClass('active');
        $('ul.navigation > li').unwrap();
        $('.collapse').on('shown.bs.collapse', function () {
            $(this).parent().find(".fa-plus").removeClass("fa-plus").addClass("fa-minus");
        }).on('hidden.bs.collapse', function () {
            $(this).parent().find(".fa-minus").removeClass("fa-minus").addClass("fa-plus");
        });


    </script>
</body>
</html>

WebAdmin/WebAdmin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">  
</head>
<body>     
    @RenderSection("scripts", required: false)
</body>
</html>